MVC_Attendance_System/Controllers/PremissionController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MVC_Attendance_System.Models;
using MVC_Attendance_System.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVC_Attendance_System.Controllers
{
    public class PremissionController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        UserManager<ApplicationUser> userManager;
        public PremissionController()
        {
            userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        }
        // GET: Premission
        [Authorize(Roles = ("Admin"))]
        public ActionResult AdminPremission(string date)
        {           
            if (date == null)
            {
               date= DateTime.Now.ToString("dd/MM/yyyy");
            }
            ViewBag.date = date;
            return View();
        }
        [Authorize(Roles = ("Admin"))]
        public ActionResult _ShowPremissions(string attend)
        {
            List<Permission> SendPremissions = new List<Permission>();
            List<Permission> _Premissions = new List<Permission>();
            _Premissions = db.permissions.ToList();
            SendPremissions = _Premissions.Where(a=>a.Date.ToString("dd/MM/yyyy").Substring(0, 10).Equals(attend)&&a.status==0).ToList();
            ViewBag.premissions = SendPremissions;
            ViewBag.students= userManager.Users.ToList<ApplicationUser>();
            return PartialView("_ShowPremissions");
        }
        [Authorize(Roles = ("Admin"))]
        public ActionResult Approved(string date, string std_id)
        {
            List<Permission> perl = db.permissions.ToList();
          
            var per = perl.FirstOrDefault(m =>(( m.StudentID == std_id) && (m.Date.ToString("dd/MM/yyyy") == date)) );
            per.status = Status.Approved;
            db.SaveChanges();
            return RedirectToAction("AdminPremission", new { date = date });
        }
     
    }
}

MVC_Attendance_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Attendance System </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {

                        <li>@Html.ActionLink("Attendance in One Date", "AttendanceInOneDate", "Student")</li>
                        <li>@Html.ActionLink("Attendance in Specific Period", "ShowStdBetweenDates", "Student")</li>

                        <li>@Html.ActionLink("Manage Permissions", "AdminPremission", "Premission")</li>
                    }
                    @if (User.IsInRole("Security"))
                    {
                        <li>@Html.ActionLink("Manage Attendance/Leave", "GetStudentsInDepartment", "Student")</li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Attendance System</p>
        </footer>
    </div>


</body>
</html>